/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.Icon;
import vista.Ventana_venta;

/**
 *
 * @author basti
 */
public class Ventana_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_Principal
     */
    public Ventana_venta vent = null;
    public Ventana_Consulta_Producto vcp = null;
    public Ventana_Reporte_Rango_Fechas vrrf=null;

    public Ventana_Principal() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    void ventanaventas() {
        if (vent == null || vent.isClosed()) {
            vent = new Ventana_venta();
            this.Ventana_general.add(vent);
            //agrandar internalframe al tamaño de la pantalla 
            try {
                vent.setMaximum(true);
                vent.show();
            } catch (Exception e) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ventana abierta", "Error", JOptionPane.ERROR_MESSAGE, null);
        }

    }
    //Centrar JINTERNALFRAME en pantalla JDESKTOPPANE
    void ventanaconsultaproductos() {
        if (vcp == null || vcp.isClosed()) {
            vcp = new Ventana_Consulta_Producto();
            this.Ventana_general.add(vcp);
            vcp.setVisible(true);
            Dimension desktopSize = Ventana_general.getSize();
            Dimension FrameSize = vcp.getSize();
            vcp.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            vcp.show();
        }else{
             JOptionPane.showMessageDialog(null, "Ventana abierta", "Error", JOptionPane.ERROR_MESSAGE, null);
        }
    }
    void ventanareporterangofechas(){
       if (vrrf == null || vrrf.isClosed()) {
            vrrf = new Ventana_Reporte_Rango_Fechas();
            this.Ventana_general.add(vrrf);
            vrrf.setVisible(true);
            Dimension desktopSize = Ventana_general.getSize();
            Dimension FrameSize = vrrf.getSize();
            vrrf.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            vrrf.show();
        }else{
             JOptionPane.showMessageDialog(null, "Ventana abierta", "Error", JOptionPane.ERROR_MESSAGE, null);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/imagenes/fondo2.jpg"));
        Image image = icon.getImage();
        Ventana_general = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        }
        ;
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu_Ventas = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Menu_Consulta_Producto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Menu_Reporte_Rango_Fechas = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        javax.swing.GroupLayout Ventana_generalLayout = new javax.swing.GroupLayout(Ventana_general);
        Ventana_general.setLayout(Ventana_generalLayout);
        Ventana_generalLayout.setHorizontalGroup(
            Ventana_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );
        Ventana_generalLayout.setVerticalGroup(
            Ventana_generalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        Menu_Ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/caja-registradora48.png"))); // NOI18N
        Menu_Ventas.setText("Venta");
        Menu_Ventas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Menu_Ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_VentasMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Ventas);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cajaproducto.png"))); // NOI18N
        jMenu2.setText("Productos");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        Menu_Consulta_Producto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        Menu_Consulta_Producto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Menu_Consulta_Producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/informacion.png"))); // NOI18N
        Menu_Consulta_Producto.setText("Datos Productos");
        Menu_Consulta_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Consulta_ProductoActionPerformed(evt);
            }
        });
        jMenu2.add(Menu_Consulta_Producto);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/reporte-de-negocios.png"))); // NOI18N
        jMenu3.setText("Reportes");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        Menu_Reporte_Rango_Fechas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Menu_Reporte_Rango_Fechas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calendario.png"))); // NOI18N
        Menu_Reporte_Rango_Fechas.setText("Rango De Fecha");
        Menu_Reporte_Rango_Fechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Reporte_Rango_FechasActionPerformed(evt);
            }
        });
        jMenu3.add(Menu_Reporte_Rango_Fechas);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/reporte_diario.png"))); // NOI18N
        jMenuItem3.setText("Reporte Diario");
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/configuraciones.png"))); // NOI18N
        jMenu4.setText("Ajustes");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ventana_general, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ventana_general)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_VentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_VentasMouseClicked
        ventanaventas();
    }//GEN-LAST:event_Menu_VentasMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void Menu_Consulta_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Consulta_ProductoActionPerformed
        ventanaconsultaproductos();
    }//GEN-LAST:event_Menu_Consulta_ProductoActionPerformed

    private void Menu_Reporte_Rango_FechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Reporte_Rango_FechasActionPerformed
        ventanareporterangofechas();
    }//GEN-LAST:event_Menu_Reporte_Rango_FechasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menu_Consulta_Producto;
    private javax.swing.JMenuItem Menu_Reporte_Rango_Fechas;
    private javax.swing.JMenu Menu_Ventas;
    private static javax.swing.JDesktopPane Ventana_general;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
